project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!materials/intro-modeling-python.qmd"
    - "!materials/intro-modeling-R.qmd"

website:
  title: "Introduction to Predictive Modeling"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Presentation

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



